esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://motivo-hub.github.io/motivo-hub/fw/"

supported_apps = ["PGI-Filter-Analyzer-1", "Matter-AllClustersApp-M5Stack-TE9", "Matter-LightingApp-TE9"]

[PGI-Filter-Analyzer-1]
chipsets = ["ESP32", "ESP32-C3"]
image.esp32 = "Full_firmware_v0.0.7.bin"
image.esp32-c3 = "firmware.9854328.bin"
ios_app_url = "https://motivo-hub.github.io/motivo-hub/fw/ReleaseNotes.md"
android_app_url = ""

[Matter-AllClustersApp-M5Stack-TE9]
chipsets = ["ESP32"]
image.esp32 = "m5stack_matter_all-clusters-app.bin"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"
android_app_url = ""

[Matter-LightingApp-TE9]
chipsets = ["ESP32", "ESP32-C3"]
image.esp32 = "esp32_matter_lighting-app.bin"
image.esp32-c3 = "esp32c3_matter_lighting-app.bin"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"
android_app_url = ""
